version: 2.1
orbs:
  node: circleci/node@3.0.0
  browser-tools: circleci/browser-tools@1.0.1
jobs:
  test:
    executor: node/default
    steps:
      - browser-tools/install-chrome
      - browser-tools/install-chromedriver
      - node/install
      - run: npm test
workflows:
  node-tests:
    jobs:
      - test
