version: 2.1
jobs:
  test:
    docker:
      - image: circleci/node:stretch-browsers
    steps:
      - checkout
      - run: |-
          curl -O http://selenium-release.storage.googleapis.com/3.0/selenium-server-standalone-3.0.1.jar
      - run: 
          command: |-
            java -jar -Dwebdriver.gecko.driver=./geckodriver selenium-server-standalone-3.0.1.jar -log selenium.log
          background: true
      - run: npm install
      - run: npm test
workflows:
  node-tests:
    jobs:
      - test
