name: test
on: [push, pull_request]

jobs:
  test:
    env:
      SELENIUM_REMOTE_URL: http://localhost:4444/wd/hub
    name: testing
    runs-on: ubuntu-20.04
    steps:
      - name: Start selenoid
        uses: Xotabu4/selenoid-github-action@v1
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: '12'
      - run: npm install
      - run: npm test
        env:
          USERNAME: ${{ secrets.USERNAME }}
          PASSWORD: ${{ secrets.PASSWORD }}
